server:
  port: 21808

spring:
  servlet:
    multipart:
      #单个数据的大小
      max-file-size: 5MB
      #总数据的大小
      max-request-size: 5MB
  profiles:
    active: dev
  application:
    name: myblog
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: ${cache.enabled}
    mode: LEGACYHTML5
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
#    jedis:
#      pool:
#        #最大连接数据库连接数,设 0 为没有限制
#        max-active: 8
#        #最大等待连接中的数量,设 0 为没有限制
#        max-idle: 8
#        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        max-wait: -1ms
#        #最小等待连接中的数量,设 0 为没有限制
#        min-idle: 0
  mail:
    # 默认为false，如果这个参数配置为 true ，那么验证会很严格，邮件认证不通过，就不能启动。
    # test-connection: true
    username: ${mail.username}
    password: ${mail.password}
    protocol: smtp
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jzh.myblog.entity.*
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true
    # \u6253\u5370 sql \u8BED\u53E5

log:
  level: info

logging:
  config: classpath:logback-spring.xml

## pagehelper分页插件配置 ##
pagehelper:
  #标识是哪一种数据库
  helperDialect: mysql
  #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  page-size-zero: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  #params: count=countSql
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  reasonable: true
  #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
  supportMethodsArguments: true


